name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

env:
  PNPM_VERSION: 7.24.3

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: npm i -g pnpm@${PNPM_VERSION}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installing pnpm
        run: npm i -g pnpm@${PNPM_VERSION}

      - name: Installing deps
        run: pnpm install

#      - name: Test
#        run: pnpm test

      - name: Building
        run: pnpm build

      - name: Copy CNAME
        run: ls;cp CNAME dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist