name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: npm i -g pnpm
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Installing pnpm
        run: npm i -g pnpm

      - name: Installing deps
        run: pnpm install

#      - name: Test
#        run: pnpm test

      - name: Building
        run: pnpm build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist